### ISSUE TITLE
2.4.2客户端消费数据出现协议界面错误-Bad frame id from server

### ISSUE THREAD

**Issue by duke88** [youzan/nsqJavaSDK#43] opened 2018-07-23 11:33 UTC
2018-07-23 18:31:40.781 [nioEventLoopGroup-9-1] ERROR [{}] Un recognized NSQ Frame! Please check NSQ protocol! 
2018-07-23 18:31:40.781 [nioEventLoopGroup-9-1] WARN  [{}] Uncaught exception in connection pipeline 
 io.netty.handler.codec.DecoderException: com.youzan.nsq.client.exception.NSQException: Bad frame id from server (1919246708). It will be disconnected!
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1304) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:921) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:135) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.0.56.Final.jar:4.0.56.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: com.youzan.nsq.client.exception.NSQException: Bad frame id from server (1919246708). It will be disconnected!
        at com.youzan.nsq.client.network.netty.NSQDecoder.decode(NSQDecoder.java:31) ~[NSQ-Client-2.4.2.jar:?]
        at com.youzan.nsq.client.network.netty.NSQDecoder.decode(NSQDecoder.java:15) ~[NSQ-Client-2.4.2.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
        ... 24 more
2018-07-23 18:31:40.782 [nioEventLoopGroup-9-1] INFO  [{}] Disconnect from nsqd 172.17.0.250:4150, GoldInRecord, 0, false ...

**Comment by DoraALin** [comment] 2018-07-30 08:56
Duplicate of #42

**Closed by DoraALin** 2018-07-30 08:56 UTC
Labels: duplicate
